export const types = {

    SEND_REQUEST_GET_ALL_USERS: 'SEND_REQUEST_GET_ALL_USERS',
    SEND_REQUEST_GET_ALL_USERS_SUCCESS: 'SEND_REQUEST_GET_ALL_USERS_SUCCESS',
    SEND_REQUEST_GET_ALL_USERS_FAILURE: 'SEND_REQUEST_GET_ALL_USERS_FAILURE',

    SEND_REQUEST_GET_DETAILS_USER: 'SEND_REQUEST_GET_DETAILS_USER',
    SEND_REQUEST_GET_DETAILS_USER_SUCCESS:
        'SEND_REQUEST_GET_DETAILS_USER_SUCCESS',
    SEND_REQUEST_GET_DETAILS_USER_FAILURE:
        'SEND_REQUEST_GET_DETAILS_USER_FAILURE',
}
